// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimeSummaryWrapper } from "./AnimeSummaryWrapper";
import type { ApiPaging } from "./ApiPaging";

export type AnimeResponse = { data: Array<AnimeSummaryWrapper>, paging: ApiPaging, };
