// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When is this usually broadcasted
 */
export type Broadcast = { day_of_the_week: string, start_time: string, };
