// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unsure about the usecase for this
 */
export type FavoriteInfo = { added_at: string, };
