// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeasonEnum } from "./SeasonEnum";

export type Season = { season: SeasonEnum, year: number, };
