// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alternative titles for the anime (and well-known registered synonyms)
 */
export type AlternativeTitles = { en: string, ja: string, synonyms: Array<string>, };
