// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiringStatus } from "./AiringStatus";
import type { AlternativeTitles } from "./AlternativeTitles";
import type { AnimeType } from "./AnimeType";
import type { Broadcast } from "./Broadcast";
import type { FavoriteInfo } from "./FavoriteInfo";
import type { Genre } from "./Genre";
import type { MainImageAsset } from "./MainImageAsset";
import type { Ranking } from "./Ranking";
import type { Season } from "./Season";

/**
 * An anime object meant for info-display (summary)
 */
export type AnimeSummary = { alternative_titles: AlternativeTitles, average_episode_duration: number, background: string | null, broadcast: Broadcast | null, 
/**
 * unix timestamp
 */
created_at: string, end_date: string | null, favorites_info: FavoriteInfo | null, genres: Array<Genre>, id: number, main_picture: MainImageAsset, mean: number | null, media_type: AnimeType, num_episodes: number, num_favorites: number, num_list_users: number, popularity: number, rank: number | null, start_date: string | null, start_season: Season | null, status: AiringStatus | null, synopsis: string, title: string, updated_at: string, ranking: Ranking | null, };
