// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from the oauth process
 */
export type OAuthResponse = { expires_in: number, access_token: string, refresh_token: string, };
