// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ranking in respective category
 */
export type Ranking = { rank: number, previous_rank: number | null, };
