// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ranking to search for (eg. Now Watching, Just Added, Airing, Trending, etc.)
 */
export type SearchRanking = "just_added" | "most_popular" | "now_watching" | "top10_airing" | "top10_upcoming" | "top_anime" | "trending";
